Mistral/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from blog.views import SignUpView, BienvenidaView, SignInView, SignOutView, SignUpView
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from .router import router


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url('', include('pwa.urls')),
    url(r'^registrate/$', SignUpView.as_view(), name='sign_up'),
    url(r'^iniciar-sesion/$', SignInView.as_view(), name='sign_in'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    url(r'^cerrar-sesion/$', SignOutView.as_view(), name='sign_out'),

    
    url(r'^password_reset_form/$', auth_views.PasswordResetView.as_view
     (template_name='blog/password_reset_form.html',
    html_email_template_name='blog/password_reset_email.html',), name='password_reset_form',),
    

    url(r'^recuperacion_password_reset_done/$', auth_views.PasswordResetDoneView.as_view(template_name='blog/password_reset_done.html',), name='password_reset_done',   ),
    url(r'^recuperacion_(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',auth_views.PasswordResetConfirmView.as_view(
            success_url=('index'),
            post_reset_login=True,
            template_name='blog/password_reset_confirm.html',
            post_reset_login_backend=( 'django.contrib.auth.backends.AllowAllUsersModelBackend'
            ), ), name='password_reset_confirm', ),

    url(r'^recuperacion_password_reset_complete/$', auth_views.PasswordResetCompleteView ,
        {'template_name': 'blog/password_reset_complete.html',}, name='password_reset_complete', ),
    url(r'^recuperacion_password_reset_done/$', auth_views.PasswordResetDoneView ,
        { 'template_name': 'blog/password_reset_done.html', }, name='password_reset_done', ),
    
    url('api/', include(router.urls))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import include, url
from . import views
from django.urls import path, include

app_name="blog"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^comprar/', views.comprar, name='comprar'),
    url(r'^contacto/$', views.contacto, name='contacto'),
    url(r'^finalizar/$', views.finalizar, name='finalizar'),
    url(r'^finalizar2/$', views.finalizar2, name='finalizar2'),
    url(r'^copete/(?P<pk>[0-9]+)/$', views.copete_detail, name='copete_detail'),
    url('^', include('django.contrib.auth.urls')),


]

blog/models.py
from django.utils.translation import ugettext as _
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Permission
from django.utils import timezone
from django.db import models
from PIL import Image, ImageOps
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save



class Formulario_Persona (models.Model):
    correo = models.EmailField(max_length=25)
    rut = models.CharField(max_length=12)
    nombre = models.CharField(max_length=25)
    def __str__(self):
        return self.nombre
    fecha = models.DateField()
    password = models.CharField(max_length=50)
    ESTADO_REGION = (
        ('estado_1', 'I Tarapaca'),
        ('estado_2', 'II Antofagasta'),
        ('estado_3', 'III Atacama'),
        ('estado_4', 'IV Coquimbo'),
        ('estado_5', 'V Valparaiso'),
        ('estado_6', 'VI Ohiggins'),
        ('estado_7', 'VII Maule'),
        ('estado_8', 'VIII Bio Bio'),
        ('estado_9', 'IX Araucania'),
        ('estado_10', 'X Los Lagos'),
        ('estado_11', 'XI Aisen'),
        ('estado_12', 'XII Magallanes y Antartica'),
        ('estado_13', 'XII Metropolitana'),
        ('estado_14', 'IVX Los Rios'),
        ('estado_15', 'XV Arica y Parinacota'),
    )

    region = models.CharField(
        max_length=25, choices=ESTADO_REGION, default='region')

    ESTADO_CUIDAD = (
        ('1', 'Arica'),
        ('2', 'Alto Hospicio'),
        ('3', 'Iquique'),
        ('4', 'Pozo Almonte'),
        ('5', 'Caldera'),
        ('6', 'Chanaral'),
        ('7', 'Copiapo'),
        ('8', 'Diego de Almagro'),
        ('9', 'El Salvador    Huasco'),
        ('10', 'Tierra Amarilla'),
        ('11', 'Vallenar'),
        ('12', 'Andacollo'),
        ('13', 'Combarbala'),
        ('14', 'Coquimbo'),
        ('15', 'El Palqui'),
        ('16', 'Illapel'),
        ('17', 'La Serena'),
        ('18', 'Los Vilos'),
        ('19', 'Montepatria'),
        ('20', 'Ovalle'),
        ('21', 'Salamanca'),
        ('22', 'Vicuna'),
        ('23', 'Algarrobo'),
        ('24', 'Cabildo'),
        ('25', 'Calle Larga'),
        ('26', 'Cartagena'),
        ('27', 'Quilpue'),
        ('28', 'Valparaiso'),
        ('29', 'Villa Alemana'),
    )

    cuidad = models.CharField(
        max_length=25, choices=ESTADO_CUIDAD, default='cuidad')

   

class Formulario_Copete (models.Model):
    imagen = models.ImageField(blank=False)
    nombre = models.CharField(max_length=30)
    def __str__(self):
        return self.nombre
    precio = models.CharField(max_length=15)
    tipo = models.CharField(max_length=15)
    
    ESTADO_CHOICE = (
        ('disponible', 'Disponible'),
        ('seleccionado', 'Seleccionado'),
        ('nodisponible', 'No Disponible'),
    )
    estado = models.CharField(max_length=25, choices=ESTADO_CHOICE)
    fecha = models.DateField()



@receiver(post_delete, sender=Formulario_Copete)
def submission_delete(sender, instance, **kwargs):
    instance.imagen.delete(False)

def get_absolute_url(self):
    return reverse(
        "questions:detail",
        kwargs={
            "pk": self.pk
            }
        )

class Perfil(models.Model):
        usuario = models.OneToOneField(User, on_delete=models.CASCADE)
        bio = models.CharField(max_length=255, blank=True)
        web = models.URLField(blank=True)

        # Python 3
        def __str__(self):
                return self.usuario.username


@receiver(post_save, sender=User)
def crear_usuario_perfil(sender, instance, created, **kwargs):
        if created:
                Perfil.objects.create(usuario=instance)


@receiver(post_save, sender=User)
def guardar_usuario_perfil(sender, instance, **kwargs):
        instance.perfil.save()

blog/forms.py
from django import forms
from .models import Formulario_Persona
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Perfil


class Formulario_Compra(forms.ModelForm):

    class Meta:
        model = Formulario_Persona
        fields = ('nombre', 'rut', 'correo', 'fecha', 'password', 'region','cuidad', )
        labels = {
            'nombre': 'Nombre y apellido',
            'rut': 'Rut',
            'correo': 'Correo',
            'fecha': 'Fecha de nacimiento',
            'password': 'Contraseña',
            'region': 'Region',
            'ciudad': 'Ciudad',
            
        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'rut': forms.TextInput(attrs={'class': 'form-control'}),
            'correo': forms.EmailInput(attrs={'class': 'form-control'}),
            'fecha': forms.DateInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
            'region': forms.Select(attrs={'class': 'form-control'}),
            'ciudad': forms.Select(attrs={'class': 'form-control'}),
            
        }

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=140, required=True)
    last_name = forms.CharField(max_length=140, required=False)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2',
        )

blog/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from .models import Formulario_Copete, Perfil
from .forms import Formulario_Compra, SignUpForm
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.views.generic import CreateView, TemplateView



def index(request):
    return render(request, 'blog/index.html', {})

def contacto(request):
    return render(request, 'blog/contacto.html', {})

def finalizar(request):
    return render(request, 'blog/finalizar.html', {})

def finalizar2(request):
    return render(request, 'blog/finalizar2.html', {})


def comprar(request):
    copetes = Formulario_Copete.objects.all()
    return render(request, 'blog/comprar.html', {'copetes': copetes})


def copete_detail(request, pk):
    copete = get_object_or_404(Formulario_Copete, pk=pk)
    if request.method == "POST":
        form = Formulario_Compra(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.usuario = request.user
            post.save()
            copete = Formulario_Copete.objects.get(pk=pk)
            copete.estado = 'seleccionado'
            copete.save()
            return redirect('blog:comprar')
    else:
        form = Formulario_Compra()
    return render(request, 'blog/copete_detail.html', {'copete': copete, 'form': form})

class SignUpView(CreateView):
    model = Perfil
    form_class = SignUpForm

    def form_valid(self, form):
        '''
        En este parte, si el formulario es valido guardamos lo que se obtiene de él 
        y usamos authenticate para que el usuario incie sesión luego de haberse registrado 
        y lo redirigimos al index
        '''
        form.save()
        usuario = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        usuario = authenticate(username=usuario, password=password)
        login(self.request, usuario)
        return redirect('/')


class BienvenidaView(TemplateView):
    template_name = 'blog/bienvenida.html'


from django.contrib.auth.views import LoginView


class SignInView(LoginView):
    template_name = 'blog/iniciar_sesion.html'


from django.contrib.auth.views import LoginView, LogoutView


class SignOutView(LogoutView):
    template_name = 'blog/index.html'
    pass

blog/templates/blog/comprar.html
{% load pwa %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% progressive_web_app_meta %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/icono.png' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/flexboxgrid.min.css' %}">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    
    <link rel="stylesheet" href="{% static 'css/agecheck.min.css' %}">
    <script src="{% static 'js/jquery.agecheck-min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <title>Mistral - Promociones</title>
    <script>
        $(document).ready(function () {

            var minAge = $('select').val();
            $('select').on('change', function () {
                minAge = $(this).val();
            });
            $('button').on('click', function () {
                sessionStorage.clear();
                $.ageCheck({ minAge: minAge });
            });

            $.ageCheck({ minAge: minAge });
        });        
    </script>
</head>

<body>
    <section id="container" class="container-fluid">
        <header class="row">
            <div class="col-xs-12 col-md-6">
                <div class="logo">
                    <img id="logo" src="../../static/img/logo.png" alt="mistral">
                </div>
            </div>

            <div class="col-xs-12 col-md-5">
                <nav id="menu" class="row">
                    {% if user.is_authenticated %}
                    <a class="col-xs-12 col-sm-3">{{ user.username }}</a>
                    <a class="col-xs-12 col-sm-3" href="{% url 'blog:comprar' %}">Promociones</a>
                    <a class="col-xs-12 col-sm-3" href="{% url 'sign_out' %}">Cerrar sesión</a>
                    {% else %}
                    <a class="col-xs-12 col-sm-3" href="{% url 'sign_in' %}">Iniciar sesión</a>
                    <a class="col-xs-12 col-sm-3" href="{% url 'sign_up' %}">Registrate</a>
                    {% endif %}
                    <a class="col-xs-12 col-sm-3" href="{% url 'blog:index' %}">Inicio</a>
                    <a class="col-xs-12 col-sm-3" href="{% url 'blog:comprar' %}">Productos</a>
                    <a class="col-xs-12 col-sm-3" href="{% url 'blog:contacto' %}">Contáctanos</a>
                </nav>
            </div>
        </header>
         <!--Copete Disponible-->
         <div style="text-align: center; color: rgb(22, 22, 22);">
            <br>
            <h1>Productos en stock</h1>
            <br>
        </div>
        <section id="section" class="row">
            {% for copete in copetes %}
            {% if copete.estado == 'disponible' %}
            {% if copete.imagen %}
            <div class="copetediv">
                <img id="copetebd" src="{{copete.imagen.url}}" alt="" width="200px">
                <div class="text-block">
                    <h4>{{copete.nombre}}</h4>
                    <a href="{% url 'blog:copete_detail' pk=copete.pk %}"></a>
                    <p id="desc" style="font-weight:bold"><br>{{copete.precio}}</p>
                    <p id="desc" style="font-weight:bold"><br>Tipo: {{copete.tipo}}</p>
                </div>
            </div>
            {% endif %}
            {% endif %}
            {% endfor %}
        </section>
        <br>

        <!--Copete no disponible-->
        <div style="text-align: center; color: rgb(22, 22, 22);">
            <h1>Productos en camino | No disponibles aun</h1>
            <br>
        </div>
        <section id="section" class="row">
            {% for copete in copetes %}
            {% if copete.estado == 'nodisponible' %}
            {% if copete.imagen %}
            <div class="copetediv">
                <img id="copetebd" src="{{copete.imagen.url}}" alt="" width="200px">
                <div class="text-block">
                    <h4>{{copete.nombre}}</h4>
                    <p id="desc" style="font-weight:bold"><br>{{copete.precio}}</p>
                    <p id="desc" style="font-weight:bold"><br>Tipo: {{copete.tipo}}</p>
                </div>
            </div>
            {% endif %}
            {% endif %}
            {% endfor %}
        </section>

        <br>

        <!--Copetes seleccionados-->
        <div style="text-align: center; color: rgb(22, 22, 22);">
            <h1>Copetes seleccionados | Carrito de compras</h1>
            <br>
        </div>
        <section id="section" class="row">
            {% for copete in copetes %}
            {% if copete.estado == 'seleccionado' %}
            {% if copete.imagen %}
            <div class="copetediv">
                <img id="copetebd" src="{{copete.imagen.url}}" alt="" width="200px">
                <div class="text-block">
                    <h4>{{copete.nombre}}</h4>
                    <p id="desc" style="font-weight:bold"><br>{{copete.precio}}</p>
                    <p id="desc" style="font-weight:bold"><br>Tipo: {{copete.tipo}}</p>
                </div>
            </div>
            
            {% endif %}
            {% endif %}
            {% endfor %}
        </section>
        <br>
        <div style="text-align: center; color: rgb(22, 22, 22);">
            <h1>Finalizar compra</h1>
            <h3>Seleccionando tu método de pago.</h3>
            <br>
            <br>
            <a id="btns" href="{% url 'blog:finalizar' %}"> Comprar </a>
        </div>
        <br>
        <br>
        <section id="creditos">
            <br>
            <p>      ~Para que puedas tomar en la comodidad de tu hogar.</p>
            <br>
        </section>
    </section>
</body>

</html>

blog/templates/blog/contacto.html
{% extends "base.html" %} {% block title %}Contacto{% endblock %} {% block content %}
<form method="POST" id="formulario">
    <h2>Número de contacto</h2>
    <h3>+569 9999 9999</h3>
    <h2>Email</h2>
    <h3>Mistral@gmail.com</h3>
</form>

{% endblock content %}

blog/templates/blog/copete_detail.html
{% load pwa %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">

<head>
    {% progressive_web_app_meta %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/icono.png' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <link rel="stylesheet" href="{% static 'css/flexboxgrid.min.css' %}">
    <script src="{% static 'js/jquery-1.6.2.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <title>Mistral - Promo</title>
</head>

<body id="index">
    <section id="container" class="container-fluid">
        <header class="row">
            <div class="col-xs-12 col-md-6">
                <div class="logo">
                    <img id="logo" src="../../static/img/logo.png" alt="mistral">
                </div>
            </div>
            <div class="col-xs-12 col-md-5">
                <nav id="menu" class="row">
                    {% if user.is_authenticated %}
                    <a class="col-xs-12 col-sm-3">{{ user.username }}</a>
                    <a class="col-xs-12 col-sm-3" href="{% url 'blog:comprar' %}">Promociones</a>
                    <a class="col-xs-12 col-sm-3" href="{% url 'sign_out' %}">Cerrar sesión</a>
                    {% else %}
                    <a class="col-xs-12 col-sm-3" href="{% url 'sign_in' %}">Iniciar sesión</a>
                    <a class="col-xs-12 col-sm-3" href="{% url 'sign_up' %}">Registrate</a>
                    {% endif %}
                    <a class="col-xs-12 col-sm-3" href="{% url 'blog:index' %}">Inicio</a>
                    <a class="col-xs-12 col-sm-3" href="{% url 'blog:comprar' %}">Productos</a>
                    <a class="col-xs-12 col-sm-3" href="{% url 'blog:contacto' %}">Contáctanos</a>
                </nav>
            </div>
        </header>
        <!--copete-->
        <div style="text-align: center; color: rgb(22, 22, 22);">
            <br>
            <h1>{{copete.nombre}}</h1>
            <br>
        </div>
        <section id="section" class="row">
            <br>
            <p style="font-weight:bold; color: #fff; padding-left: 2%"> {{copete.descripcion}}</p>
            <p style="font-weight:bold; color: aliceblue">Tipo: {{copete.tipo}}</p>
            <img id="copetebd" src="{{ copete.imagen.url }}" alt="" width="40%" style="box-shadow: 1px 1px 6px rgba(0, 0, 0, 0.548);">
        </section>
        <div style="text-align: center; color: rgb(22, 22, 22);">
            <br>
            <h1>Formulario de verificación</h1>
            <h4>Información para corroborar identidad.</h4>
            <br>
        </div>

        <!--Formulario seleccion-->
        <section id="section" class="row">
            <form method="post" class="post-form" id="formulario">{% csrf_token %}
                {% if user.is_authenticated %}
                {{ form.as_p }}
                <button type='submit' class="save btn btn-default">   Seleccionar   </button>
                {% else %}
                <div style="text-align: center; color: rgb(22, 22, 22);">
                        <br>
                        <h1>Porfavor inicie sesión</h1>
                        <br>
                        <br>
                    </div>
                {% endif %}
            </form>
        </section>
        <section id="creditos">
                <br>
                <p>      ~Para que puedas tomar en la comodidad de tu hogar.</p>
                <br>
            </section>
    </section>
</body>

</html>

blog/templates/blog/finalizar.html
{% load pwa %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
  {% progressive_web_app_meta %}
  <meta charset="UTF-8">
  <meta name="viewport"
    content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="shortcut icon" type="image/png" href="{% static 'img/icono.png' %}">
  <link rel="stylesheet" href="{% static 'css/flexboxgrid.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/finalizar.css' %}">
  <script src="{% static 'js/jquery-1.6.2.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
  <title>Mis Mistral</title>
  <title>{% block title %}{% endblock %}</title>
</head>

<body>
  <section id="container" class="container-fluid">
    <header class="row">
      <div class="col-xs-12 col-md-6">
        <div class="logo">
          <img id="logo" src="../../static/img/logo.png" alt="mistral">
        </div>
      </div>
      <div class="col-xs-12 col-md-5">
        <nav id="menu" class="row">
          {% if user.is_authenticated %}
          <a class="col-xs-12 col-sm-3">{{ user.username }}</a>
          <a class="col-xs-12 col-sm-3" href="{% url 'blog:comprar' %}">Comprar</a>
          <a class="col-xs-12 col-sm-3" href="{% url 'sign_out' %}">Cerrar sesión</a>
          {% else %}
          <a class="col-xs-12 col-sm-3" href="{% url 'sign_in' %}">Iniciar sesión</a>
          <a class="col-xs-12 col-sm-3" href="{% url 'sign_up' %}">Registrate</a>
          {% endif %}
          <a class="col-xs-12 col-sm-3" href="{% url 'blog:index' %}">Inicio</a>
          <a class="col-xs-12 col-sm-3" href="{% url 'blog:comprar' %}">Productos</a>
          <a class="col-xs-12 col-sm-3" href="{% url 'blog:contacto' %}">Contáctanos</a>
        </nav>
      </div>
    </header>
    <div style="text-align: center; color: rgb(22, 22, 22);">
      <br>
      <h1>Usuarios</h1>
      <br>
    </div>
    <section id="section" class="row">


      <div class="modal" style="padding-top: 100px;">
        <div class="modal__container">

          <div class="modal__content">
            <h2 style="padding-top: 20px;">Detalles de compra</h2>
            <br>
            <form>
              <ul class="form-list">


                <h4>Seleccione metodo de pago.</h4>
                <br>
                <li class="form-list__row">
                  <label for="id_modopago_0">Débito</label>
                  <span class="radio"><input id="id_modopago_0" name="modopago" type="radio" value="debito"
                      style="width: 40%;" required></span>

                </li>
                <li class="form-list__row">
                  <label for="id_modopago_1">
                    Crédito
                    <span class="radio"><input id="id_modopago_1" name="modopago" type="radio" value="credito"
                        style="width: 20%;" required></span>
                  </label>
                </li>
                <br>
                <br>
                <h4>Seleccione entrega de producto.</h4>
                <br>
                <li class="form-list__row">
                  <label for="id_entrega_0">
                    Llevar a domicilio
                    <span class="radio"><input id="id_entrega_0" name="entrega" type="radio" value="domicilio"
                        style="width: 30%;" required></span>
                  </label>
                </li>
                <br>
                <li class="form-list__row">
                  <label for="id_entrega_1">
                    Despachar en tienda
                    <span class="radio"><input id="id_entrega_1" name="entrega" type="radio" value="tienda"
                        style="width: 24%;" required></span>
                  </label>
                </li>
                <br>

                <li class="form-list__row">
                  <label style="padding-top: 10px;">Número de tarjeta</label>
                  <div id="input--cc" class="creditcard-icon">
                    <input type="text" name="cc_number" required="" />
                  </div>
                </li>
                <li class="form-list__row form-list__row--inline">
                  <div>
                    <label>Fecha de expiración</label>
                    <div class="form-list__input-inline">
                      <input type="text" name="cc_number" placeholder="MM" minlength="2" maxlength="2" required="" />
                      <input type="text" name="cc_number" placeholder="AA" minlength="2" maxlength="2" required="" />
                    </div>
                  </div>
                  <div>
                    <label>
                      CVC
                    </label>
                    <input type="text" name="cc_cvc" placeholder="123" minlength="3" maxlength="4" required="" />
                  </div>
                </li>
                <li class="form-list__row form-list__row--agree">
                  <label>
                    <input type="checkbox" name="save_cc" checked="checked">
                    Guardar datos para una futura compra .
                  </label>
                </li>
                <li style="padding-left: 42%;">
                  <a class="button" style="color: #ffffff; text-decoration: none;"
                      href="{% url 'blog:finalizar2' %}"> Pagar</a>
                </li>
              </ul>
            </form>
          </div> 
        </div>
      </div>

    </section>
    <br><br><br>
    <section id="creditos">
      <br>
      <p>      ~Para que puedas tomar en la comodidad de tu hogar.</p>
      <br>
    </section>
  </section>
</body>

</html>

blog/templates/blog/finalizar2.html
{% extends "base.html" %} {% block title %}Finalizar{% endblock %} {% block content %}
<form method="POST" id="formulario">
    <h2>    Gracias por preferir botilleria Mistral</h2>
    <br>
    <h4 style="margin-left: 20%;">Su pedido está en proceso.</h4>
    <br>
    <br>
    <br>
    <a id="btns" style="margin-left: 200px;" href="{% url 'blog:index' %}"> ir a inicio</a>

</form>

{% endblock content %}

blog/templates/blog/iniciar_sesion.html
{% extends "base.html" %} {% block title %}Inicia Sesión{% endblock %} {% block content %}
<form method="POST" id="formulario">
    {% csrf_token %} {{ form.as_p }}
    <input type="submit" name="submit">
    <a href="{% url 'password_reset_form' %}" >Olvidé mi contraseña</a>
</form>
<br>
<p>
    <strong>Inicie con: </strong>
</p>
<a href="{% url 'social:begin' 'google-oauth2' %}"><img id="google" src="../../static/img/google-icon.png" alt=""></a>
<br>
{% endblock content %}

blog/templates/blog/password_reset_complete.html
{% extends "base.html" %}

{% block title %}{% endblock %}

{% block content %}

<h2>Su contraseña se reestableció correctamente.</h2>

<p><a href="{% url 'iniciar-sesion' %}">Iniciar sesion</a></p>

{% endblock  %}

blog/templates/blog/password_reset_confirm.html
{% extends "base.html" %}

{% block title %}{% endblock %}

{% block content %}

{% if validlink %}

<form method="POST" id="formulario">
    {% csrf_token %}

    <p>Solicitar nueva contraseña</p>

    {{ form.new_password1.errors }}
    <label for="id_new_password1">Nueva contraseña:</label> 
    {{ form.new_password1 }}

    {{ form.new_password2.errors }}
    <label for="id_new_password2">Confirmar contraseña:</label> 
    {{ form.new_password2 }}

    <input type="submit" name="submit" evalue="Enviar" >

</form>    

{% else %}

<h2>Enlace inválido.</h2>

{% endif %}

{% endblock content %}

blog/templates/blog/password_reset_done.html
{% extends "base.html" %}

{% block title %}{% endblock %}

{% block content %}
    <h3 style="color: white;">Te hemos enviado un correo con un enlace para reestablecer tu contraseña.</h3> 
{% endblock content %}

blog/templates/blog/password_reset_email.html
Solicitaste reestablecer tu contraseña.
Click en el siguiente link para crear una nueva.
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token % }
{% endblock  %}

Tu nombre de usuario es: {{ user.get_username }}

blog/templates/blog/password_reset_form.html
{% extends "base.html" %}

{% block title %}{% endblock %}

{% block content %}

    <form method="POST" id="formulario">
        {% csrf_token %}
        <p>Recuperar contraseña</p>
        <label for="id_email">Correo:</label> {{ form.email }}
        <input type="submit" name="submit" evalue="Enviar" >
    </form>    
{% endblock  %}

blog/templates/blog/perfil_form.html
{% extends "base.html" %}

{% block title %}Registrate{% endblock %}

{% block content %}
    <form action="" method="POST" id="formulario">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit">
    </form>    
{% endblock content %}